Repository PCON-Hacktoberfest-2022/ClockSet-v1, pull requests merged in 2022-10, with the labels that each got.

#4 fix: datetime to indian time format
  contest.js
Labels: hacktoberfest, hacktoberfest-accepted

#6 Contest Time title added and styled
  contest.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 Dark mode enabled
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 Ui improved and moment js added to make working with date and time easier
  .gitignore
  contest.js
  index.css
  index.html
  index.js
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#21 Added icons and logos
  images/leetcode.png
  images/moon.png
  images/sun.png
  index.css
  index.html
Labels: hacktoberfest-accepted

#25 footer added
  index.css
  index.html
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#28 favicon added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#30 modified footer text and css colors
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#32 Add Codeforces Contest
  contest.js
  images/codeforces.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#34 localstorage enabled
  dark.js
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#33 Fixed some grammatical errors
  README.md
Labels: documentation, hacktoberfest-accepted

#41 AtCoder Contest Calender
  contest.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#44 No hardcoded contest
  contest.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#47 fix: remove hardcoded divs codechef and at_coder
  contest.js
  images/at_coder.png
  images/codechef.svg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#48 Updated the Footer Styling to look it more minimal
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#49 KickStart Column Added in your Extension
  contest.js
  images/kick_start.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#51 css changed
  index.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#55 Hackerearth API added.
  contest.js
  images/hacker_earth.png
  index.html
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#57 Hackerrank API added
  contest.js
  images/hacker_rank.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#58 UI bug fixed
  contest.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#59 Filter Feature added
  contest.js
  index.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#61 Optimize code
  contest.js
  index.html
Labels: enhancement, hacktoberfest-accepted

#62 Changed header to black
  index.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#65 added new style
  index.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#66 improved
  index.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#67 second PR
  index.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
